 -------------------------- 9/23/25 ------------------------
# Ch7 Array-Oriented Programming with NumPy

- High-performance, richly functional n-dimensional array type called ndarray.
- Critical in big-data processing, AI applications and much more.
- Functional-style programming with internal iteration makes array-oriented manipulations concise and straightforward, and reduces the possibility of error.

## 7.2 Creating arrays from Existing Data¶
- Creating an array with the array function
- Argument is an array or other iterable
- Returns a new array containing the argument’s elements

In [1]:
import numpy as np # library contains arrays 

numbers = np.array([3,5,6,7,2])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
numbers

array([3, 5, 6, 7, 2])

### Multidimensional Arguments

In [5]:
np.array([[1,5,6],[6,8,3]])

array([[1, 5, 6],
       [6, 8, 3]])

## 7.3 array Attributes
- attributes enable you to discover information about its structure and contents

In [8]:
import numpy as np

In [9]:
integers = np.array([[3,5,6],[3,1,5]])
integers

array([[3, 5, 6],
       [3, 1, 5]])

NumPy does not display trailing 0s:

In [11]:
floats= np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

### Determining an array’s Element Type

In [12]:
integers.dtype

dtype('int64')

In [13]:
floats.dtype

dtype('float64')

In [14]:
numbers.dtype

dtype('int64')

### Determining an array’s Dimensions

- ndim contains an array’s number of dimensions
- shape contains a tuple specifying an array’s dimensions

In [15]:
integers.ndim

2

In [17]:
numbers.ndim

1

In [18]:
integers.shape

(2, 3)

In [19]:
numbers.shape

(5,)

### Determining an array’s Number of Elements and Element Size
- view an array’s total number of elements with size
- view number of bytes required to store each element with itemsize

In [20]:
integers.size

6

In [21]:
floats.size

5

In [23]:
floats.itemsize

8

### Iterating through a Multidimensional array’s Elements

In [26]:
for row in integers: 
    for column in row:
        print(column, end='  ')
    print()

3  5  6  
3  1  5  


- Iterate through a multidimensional array as if it were one-dimensional by using flat

In [27]:
for i in integers.flat: 
    print(i, end = '  ')

3  5  6  3  1  5  

## 7.4 Filling arrays with Specific Values
- Functions zeros, ones and full create arrays containing 0s, 1s or a specified value, respectively

In [29]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

- For a tuple of integers, these functions return a multidimensional array with the specified dimensions

In [30]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
np.full((3,5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

## 7.5 Creating arrays from Ranges
- NumPy provides optimized functions for creating arrays from ranges

### Creating Integer Ranges with arange

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

### Creating Floating-Point Ranges with linspace
- Produce evenly spaced floating-point ranges with NumPy’s linspace function
- Ending value is included in the array

In [36]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshaping an array
- array method reshape transforms an array into different number of dimensions
- New shape must have the same number of elements as the original

In [37]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Displaying Large arrays
- When displaying an array, if there are 1000 items or more, NumPy drops the middle rows, columns or both from the output

In [39]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [41]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

------------------------- 9/24/25 -----------------------

# 7.6 List vs. array Performance: Introducing %timeit
- Most array operations execute significantly faster than corresponding list operations
- IPython %timeit magic command times the average duration of operations

### Magics 
- are special commands available in IPython and Jupyter Notebooks.
- They are not part of standard Python syntax — they’re extensions that make interactive work easier.
- They always start with % (line magics) or %% (cell magics).

### Two kinds of magics
**Line magics (%)**
Apply to a single line. Example:

- %timeit [x**2 for x in range(1000)]  # times this one line


**Cell magics (%%)**
Apply to an entire cell. Example:

- %%time
- squares = [x**2 for x in range(10_000_000)]
- print(len(squares))

### Timing the Creation of a List Containing Results of 6,000,000 Die Rolls¶


- By default, %timeit executes a statement in a loop, and it runs the loop seven times
- If you do not indicate the number of loops, %timeit chooses an appropriate value
- After executing the statement, %timeit displays the statement’s average execution time, as well as the standard deviation of all the executions

In [71]:
import random
# specifically for JUPYTER : 
%time
rolls_list = [random.randrange(1, 7) for _ in range(6_000_000)]

CPU times: total: 0 ns
Wall time: 9.54 μs


In [72]:
## FOR PYTHON IDE
%timeit rolls_list = \
   [random.randrange(1, 7) for i in range(0, 6_000_000)]

6.78 s ± 396 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Timing the Creation of an array Containing Results of 6,000 Die Rolls

In [37]:
import numpy as np
%timeit rolls = np.random.randint(1,7,6000)

105 μs ± 4.74 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Customizing the %timeit Iterations

In [38]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000)


171 μs ± 14.4 μs per loop (mean ± std. dev. of 2 runs, 3 loops each)


### Other IPython Magics

IPython provides dozens of magics for a variety of tasks. For a complete list, see the [IPython magics documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html).  
Here are a few helpful ones:

- `%load` — read code into IPython from a local file or URL.
- `%save` — save snippets to a file.
- `%run` — execute a `.py` file from IPython.
- `%precision` — change the default floating-point precision for IPython outputs.
- `%cd` — change directories without having to exit IPython first.
- `%edit` — launch an external editor (useful for modifying more complex snippets).
- `%history` — view a list of all snippets and commands executed in the current IPython session.

### 7.7 array Operators
- array operators perform operations on entire arrays.
- Can perform arithmetic between arrays and scalar numeric values, and between arrays of the same shape.

In [41]:
import numpy as np

number = np.arange(1,6)
number

array([1, 2, 3, 4, 5])

In [42]:
number * 2

array([ 2,  4,  6,  8, 10])

In [43]:
number ** 3

array([  1,   8,  27,  64, 125])

In [44]:
number # number is unchanged by arithmetic operators 

array([1, 2, 3, 4, 5])

In [46]:
number += 10
number

array([21, 22, 23, 24, 25])

### Broadcasting
- Arithmetic operations require as operands two arrays of the same size and shape.
- numbers * 2 is equivalent to numbers * [2, 2, 2, 2, 2] for a 5-element array.
- Applying the operation to every element is called broadcasting.
- Also can be applied between arrays of different sizes and shapes, enabling some concise and powerful manipulations.

### Arithmetic Operations Between arrays
- Can perform arithmetic operations and augmented assignments between arrays of the same shape

In [56]:
number2 = np.linspace(1.1, 5.5, 5)
number2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [57]:
number * number2

array([ 23.1,  48.4,  75.9, 105.6, 137.5])

### Comparing arrays
- Can compare arrays with individual values and with other arrays
- Comparisons performed element-wise
- Produce arrays of Boolean values in which each element’s True or False value indicates the comparison result

In [58]:
number >=13

array([ True,  True,  True,  True,  True])

In [60]:
number2 < number

array([ True,  True,  True,  True,  True])

# 7.8 NumPy Calculation Methods
- These methods ignore the array’s shape and use all the elements in the calculations.
- Consider an array representing four students’ grades on three exams:

In [61]:
import numpy as np

grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

- Can use methods to calculate sum, min, max, mean, std (standard deviation) and var (variance)
- Each is a functional-style programming reduction

In [62]:
grades.sum()

np.int64(1054)

In [64]:
grades.min()

np.int64(70)

In [65]:
grades.max()

np.int64(100)

In [66]:
grades.mean()

np.float64(87.83333333333333)

In [67]:
grades.std()

np.float64(8.792357792739987)

In [68]:
grades.var()

np.float64(77.30555555555556)

# Calculations by Row or Column
- You can perform calculations by column or row (or other dimensions in arrays with more than two dimensions)
- Each 2D+ array has one axis per dimension
- In a 2D array, axis=0 indicates calculations should be column-by-column

In [69]:
grades.mean(axis =0)

array([95.25, 85.25, 83.  ])

In [70]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])