 -------------------------- 9/23/25 ------------------------
# Ch7 Array-Oriented Programming with NumPy

- High-performance, richly functional n-dimensional array type called ndarray.
- Critical in big-data processing, AI applications and much more.
- Functional-style programming with internal iteration makes array-oriented manipulations concise and straightforward, and reduces the possibility of error.

## 7.2 Creating arrays from Existing Data¶
- Creating an array with the array function
- Argument is an array or other iterable
- Returns a new array containing the argument’s elements

In [1]:
import numpy as np # library contains arrays 

numbers = np.array([3,5,6,7,2])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
numbers

array([3, 5, 6, 7, 2])

### Multidimensional Arguments

In [5]:
np.array([[1,5,6],[6,8,3]])

array([[1, 5, 6],
       [6, 8, 3]])

## 7.3 array Attributes
- attributes enable you to discover information about its structure and contents

In [8]:
import numpy as np

In [9]:
integers = np.array([[3,5,6],[3,1,5]])
integers

array([[3, 5, 6],
       [3, 1, 5]])

NumPy does not display trailing 0s:

In [11]:
floats= np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

### Determining an array’s Element Type

In [12]:
integers.dtype

dtype('int64')

In [13]:
floats.dtype

dtype('float64')

In [14]:
numbers.dtype

dtype('int64')

### Determining an array’s Dimensions

- ndim contains an array’s number of dimensions
- shape contains a tuple specifying an array’s dimensions

In [15]:
integers.ndim

2

In [17]:
numbers.ndim

1

In [18]:
integers.shape

(2, 3)

In [19]:
numbers.shape

(5,)

### Determining an array’s Number of Elements and Element Size
- view an array’s total number of elements with size
- view number of bytes required to store each element with itemsize

In [20]:
integers.size

6

In [21]:
floats.size

5

In [23]:
floats.itemsize

8

### Iterating through a Multidimensional array’s Elements

In [26]:
for row in integers: 
    for column in row:
        print(column, end='  ')
    print()

3  5  6  
3  1  5  


- Iterate through a multidimensional array as if it were one-dimensional by using flat

In [27]:
for i in integers.flat: 
    print(i, end = '  ')

3  5  6  3  1  5  

## 7.4 Filling arrays with Specific Values
- Functions zeros, ones and full create arrays containing 0s, 1s or a specified value, respectively

In [29]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

- For a tuple of integers, these functions return a multidimensional array with the specified dimensions

In [30]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
np.full((3,5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

## 7.5 Creating arrays from Ranges
- NumPy provides optimized functions for creating arrays from ranges

### Creating Integer Ranges with arange

In [33]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

### Creating Floating-Point Ranges with linspace
- Produce evenly spaced floating-point ranges with NumPy’s linspace function
- Ending value is included in the array

In [36]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshaping an array
- array method reshape transforms an array into different number of dimensions
- New shape must have the same number of elements as the original

In [37]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Displaying Large arrays
- When displaying an array, if there are 1000 items or more, NumPy drops the middle rows, columns or both from the output

In [39]:
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [41]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])