### Lab 3: Box Average
- apply lab 2 on a 2D array
- In this lab you will be moving an array or a "box" from the start into the end of the list. One way of seeing this is a box moving around the 2d array from the beginning of the list till the end.
- box size 9 elements
- Using the features provided to you by numpy and implement the logic above. You need to provide me with a pure function that only takes a 2D array as its input parameters. To get your dimensions you can use n, m = input.shape
- ndarray as your output that is the result value
 -  your targeted dimensions need to be ((n-2)(m-2)
 -  Then within your loop you would need to slice your input array into an ndarray as you see above and use the mean method on it.
 -  Once done return the result



In [48]:
import numpy as np

def pureFunction(superArray): # function to take my array as iput 
    n, m = superArray.shape # check ch7 notes; shape is an attribute of ndarray that returns a tuple containing dimensions of the array 
    # so in my case 5 x 5 
    results = np.full((n - 2, m - 2),9999999999999, dtype=float) # here can use any of the 7.4 funcitons; zeros, ones, full or range to overcomplicate 
    #the size of the dimensions is reduced by 2 to exclude border rows since they are not incl. into output array
    #also data type is set to float to get 2 precision in the resutls - otherwise returns rounded integers - but then it prints 9999s in scientifict notation :) 
    print(results) # just testing 
    print("--- Original array: -----")
    # Need to iterate while excluding borders 
    for i in range(1, n - 1): # loop starts from indx 1 and ends indx-1 to skip the first nad last rows 
        for j in range(1, m - 1): # same for columns, skip 1st and 5th 
            # Slice a 3x3 box around the current element (i, j)
            # now need to select a subset from the main array (ch.7.10 notes) #to use a slice 
            # 0:4, 0:3
            subset = superArray[i-1:i+2, j-1:j+2] # row:column indexed. so 1-1:1+3 rows : 1-1:1+2 columns 0:3 (2 since not inclusive) 
    
            # now need to get the mean and store in ndarray in appropriate position i -1 j -1 
            results[i-1, j-1] = np.mean(subset)
    return np.round(results,2) # rounding to .2


testScores = np.array([[33, 55, 66, 77, 22],[11, 22, 33, 44, 55],[99, 88, 77, 66, 55],[73, 92, 73, 28, 21],[3, 6, 2, 8, 5]])

result = pureFunction(testScores)
print(testScores)
print("--- and here is the Box Average: -----")
print(result)


[[1.e+13 1.e+13 1.e+13]
 [1.e+13 1.e+13 1.e+13]
 [1.e+13 1.e+13 1.e+13]]
--- Original array: -----
[[33 55 66 77 22]
 [11 22 33 44 55]
 [99 88 77 66 55]
 [73 92 73 28 21]
 [ 3  6  2  8  5]]
--- and here is the Box Average: -----
[[53.78 58.67 55.  ]
 [63.11 58.11 50.22]
 [57.   48.89 37.22]]
